// Auto generated by utensor-cli

#ifndef __MODELS_DEEP_MLP1_H
#define __MODELS_DEEP_MLP1_H
#include "uTensor/core/context.hpp"
void get_deep_mlp1_ctx(Context& ctx, Tensor* input_0);
#endif // __MODELS_DEEP_MLP1_H